### ISSUE TITLE
HTTP client with backoff but no retries

### ISSUE THREAD

**Issue by blake256** [pokt-foundation/pocket-go#72]
Just curious, what's the point of having a retrier and setting `defaultHTTPClientRetries` to 0?

https://github.com/pokt-foundation/pocket-go/blob/master/internal/client/client.go

**Comment by pablocampogo** [comment]
You're right, we should not set a retrier if default retries is 0. I can do a PR fixing it later.

**Comment by pablocampogo** [comment]
Thinking it better, I think is more robust to let it as it is right now. In a future we could want to change the `defaultHTTPClientRetries` and we could forget to add the custom `retrier`
